name: Build and Push Docker Image to Docker Hub
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALIYUN_REGISTRY_USER }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
 
    - name: Build Docker Image
      run: docker build -t your-docker-username/your-repo-name .
 
    - name: Push Docker Image
      run: docker push your-docker-username/your-repo-name
